language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn

script:
  - yarn
  - yarn build --base-href /todo-app/
  - mv dist/todo-app/index.html dist/todo-app/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: cf074fbf35ad0492f63dd5edcc58e4a136c6552c
  local_dir: dist/todo-app
  on:
    branch: master
