language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn

script:
  - yarn
  - yarn build --base-href /todo-app/
  - mv dist/todo-app/index.html dist/todo-app/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: e8b9cc20bb8d339dd1a1b2651227150b708c6035
  local_dir: dist/todo-app
  on:
    branch: master
